### PR TITLE
AUI-1997 Test

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Can you add the entry to the scheduler HISTORY file?

**Comment by brandizzi** [comment]
Done. All changes were applied to the same branch so you can fetch it again now.

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Pull request submitted to https://github.com/mairatma/alloy-ui/pull/251. [See changes here.](https://github.com/thiago-rocha/alloy-ui/compare/4498d15~1...4498d15) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
