### PR TITLE
AUI-2038 (master-deprecated)

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Hi @blzaugg, I added some inline comments. Can you take a look at them?

**Comment by thiago-rocha** [comment]
Can you add the entry to the form-builder-field-deprecated HISTORY files?

**Comment by blzaugg** [comment]
> Can you add the entry to the form-builder-field-deprecated HISTORY files?
Pushed HISTORY.md

**Comment by thiago-rocha** [comment]
@blzaugg , this pr has a lot of commits, most of them are a "Merge branch 'master' into master-deprecated". So could you send me this pr again only with yours commits?

**Comment by blzaugg** [comment]
https://github.com/thiago-rocha/alloy-ui/pull/38

**Comment by blzaugg** [comment]
https://github.com/thiago-rocha/alloy-ui/pull/49

**Pull request closed without merging**
