### PR TITLE
AUI-2037

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
AUI-2038 https://github.com/thiago-rocha/alloy-ui/pull/40

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Since this code was added here we need to add test cases for it on aui-form-validator.js.

**Comment by thiago-rocha** [comment]
Hey @blzaugg, I added some inline comments. Can you take a look at them?

**Comment by blzaugg** [comment]
@thiago-rocha, I need to address some other, time sensitive, customer tickets like this one. Would you have time to address the source formatting and tests? I'm not going to be able get back to this one until mid next week.

**Comment by thiago-rocha** [comment]
No problem, I will add the sf commit, but when you have time take a look at these inline comments that I added and also so read this contributing rules http://alloyui.com/contributing/

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by blzaugg** [comment]
https://github.com/blzaugg/alloy-ui/pull/57

**Pull request closed without merging**
