### PR TITLE
AUI-1940 - make date validator accept brazilian format dd/mm/yyyy

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Pull request submitted to https://github.com/linolaoj/alloy-ui/pull/1. [See changes here.](https://github.com/thiago-rocha/alloy-ui/compare/48a9ee5~1...48a9ee5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
@linolaoj , I sent to you a pull request with a source formatting. Could you please add a test case for your changes and rebase with master?

**Comment by linolaoj** [comment]
Hi @thiago-rocha  , new pull request with tests and source format https://github.com/thiago-rocha/alloy-ui/pull/15

**Pull request closed without merging**
