### PR TITLE
AUI-2077

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
Please merge https://github.com/thiago-rocha/alloy-ui/pull/65 first.

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Pull request submitted to https://github.com/mairatma/alloy-ui/pull/306. [See changes here.](https://github.com/thiago-rocha/alloy-ui/compare/ed27ff6~1...ed27ff6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
