### PR TITLE
AUI-2058

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @thiago-rocha,

Attached is an update for http://issues.liferay.com/browse/AUI-2058.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jonmak08** [comment]
Hey @thiago-rocha,

I just force pushed up this branch with the ```top``` styles removed.

Please let me know if you have any questions. Thanks!

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Pull request submitted to https://github.com/mairatma/alloy-ui/pull/307. [See changes here.](https://github.com/thiago-rocha/alloy-ui/compare/570aec0~1...570aec0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
