### PR TITLE
AUI-2112

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @thiago-rocha,

Attached is an update for https://issues.liferay.com/browse/AUI-2112.

I could not think of a way to test the responsiveness of this module since it resizes when the window resizes.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Hey @jonmak08 ,

Make aui-video responsive is awesome!!!!

But before I send this pr to Maira, you guys need to add a test case for this change
and I don't understand why you guys is adding this attribute `aspectRatio` could you please explain this to me?

**Comment by jonmak08** [comment]
Hey @thiago-rocha,

I don't think we necessarily need the ```aspectRatio``` attribute, since we can get that from the height and the width.  We can change that to a private property instead.

For the test case, is there a way to resize the browser window?  I could not find a way to resize it using the YUI unit tests.

Please let me know if you have any questions. Thanks!

**Comment by thiago-rocha** [comment]
Hey @jonmak08 ,

To the test case you can try something like this:

```
if (Y.UA.ie === 8) {
    // Calling the function  that handle the resize window event.
}
else {
    Y.one(Y.config.win).set('innerWidth', XXX);
    Y.one(Y.config.win).simulate('resize');
}
```

And I still don't get the point of the `aspectRatio` attribute. Let me say what I understood by this pr:

We need to keep the whole video visible in all different screen sizes, so we need resize the aui-video `boundingBox` to fit the window size. The aspect ratio is related with the video resolution, and we don`t need change the video for keep the `boundingBox`. So for this case we don`t need the `aspectRatio` attribute.
Do I make myself clear?

**Comment by jonmak08** [comment]
Hey @thiago-rocha,

Yup, I will remove the ```aspectRatio``` attribute.  I just wanted to add the test as well.  Thanks!

**Comment by jonmak08** [comment]
Hey @thiago-rocha,

I have just pushed up all the changes to this pull request again.  It has the unit tests as well as the removal of the ```aspectRatio``` attribute.

Please let me know if you have any questions. Thanks!

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Pull request submitted to https://github.com/mairatma/alloy-ui/pull/330. [See changes here.](https://github.com/thiago-rocha/alloy-ui/compare/6362880~1...6362880) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
