### PR TITLE
AUI-3084

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @thiago-rocha,

Attached is an update for http://issues.liferay.com/browse/AUI-3084.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
@jonmak08  The code lgtm, but it's missing a test for this use case that's being fixed. It will even help me understand what's being fixed, I'm not sure I see it at the moment. Can you add the test?

**Comment by jonmak08** [comment]
Hey @thiago-rocha,

@jonathanmccann will be adding the unit tests for this and we will send an updated pull request.

Please let me know if you have any questions. Thanks!

**Comment by jonathanmccann** [comment]
Pull request with test - https://github.com/jonmak08/alloy-ui/pull/350

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/thiago-rocha/alloy-ui/pull/99

**Pull request closed without merging**
