### PR TITLE
LPS-64993

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @thiago-rocha,

Attached is an update for http://issues.liferay.com/browse/LPS-64993.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Hi @jonmak08 .

The code looks good, but before I send this pr to Maira could you add a test for the fix and update the HISTORY.md with this new change?

**Comment by jonmak08** [comment]
Hey @kienD,

Can you add a unit test for this pull request?

**Comment by jonmak08** [comment]
Hey @thiago-rocha,

I have pushed in the unit tests for this fix.  Can you please review?

Please let me know if you have any questions. Thanks!

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by thiago-rocha** [comment]
Pull request submitted to https://github.com/mairatma/alloy-ui/pull/331. [See changes here.](https://github.com/thiago-rocha/alloy-ui/compare/5386545~1...5386545) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
